# SearXNG settings

use_default_settings: true

general:
  debug: false
  instance_name: "SearXNG"

search:
  safe_search: 2
  autocomplete: 'duckduckgo'
  formats:
    - html
    - json
  method: POST

server:
  secret_key: "ultrasecretkey"
  limiter: false
  image_proxy: true
  # public URL of the instance, to ensure correct inbound links. Is overwritten
  # by ${SEARXNG_BASE_URL}.
  base_url: "http://localhost:8112/"

outgoing:
  request_timeout: 3.0

# preferences:
#   lock:
#     - autocomplete
#     - method

# engines:
#
#   - name: fdroid
#     disabled: false
#
#   - name: apk mirror
#     disabled: false
#
#   - name: mediathekviewweb
#     categories: TV
#     disabled: false

# engines:
#   - name: duckduckgo
#     disabled: false
#     categories: general
#     timeout: 2.0

#   - name: wikipedia
#     disabled: false
#     categories: knowledge
#     timeout: 2.0

#   # Voor betaalde/official API's (stabieler):
#   - name: google_cs            # Google Custom Search JSON API
#     disabled: true
#     api_key: "${GOOGLE_API_KEY}"
#     engine: google_cs
#     cx: "${GOOGLE_CX}"
#     categories: general
#     timeout: 3.0